server:
  port: 8080

spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  data:
    mongodb:
      database: example
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password: sa
  liquibase:
    enabled: true
    change-log: classpath:liquibase.yml
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
