spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password: sa
#    initialization-mode: always
#    schema: schema.sql
#    data: data.sql
  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql
  liquibase:
    enabled: true
    change-log: classpath:liquibase.yml
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true