server:
  port: 8080

spring:
  data:
    mongodb:
      database: example
      host: localhost

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2


mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongo.mongock
  mongo-db:
    host: localhost
    port: 27017
    database: example
    write-concern:
      journal: false
    read-concern: local
